name: Generate Snake

on:
  schedule:
    # Se ejecuta automáticamente cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Te permite ejecutarlo manualmente cuando quieras
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Genera el archivo de la culebrita usando tu usuario
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Guarda la imagen generada en una rama oculta llamada "output"
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
